name: ARM

on: [push, pull_request]

# Building using the github runner environement directly.
jobs:
  glop:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build env image
      run: make --directory=cmake arm_glop_env
    - name: Build devel image
      run: make --directory=cmake arm_glop_devel
    - name: Build project
      run: make --directory=cmake arm_glop_build
    - name: Test project
      run: make --directory=cmake arm_glop_test

  or-tools:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build env image
      run: make --directory=cmake arm_or-tools_env
    - name: Build devel image
      run: make --directory=cmake arm_or-tools_devel
    - name: Build project
      run: make --directory=cmake arm_or-tools_build
    - name: Test project
      run: make --directory=cmake arm_or-tools_test
